name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: skaldarnar/gh-extension-precompile@trunk
        with:
          go_stable: 'false'
          go_version: "1.18.0-beta1"
